#!/bin/bash
set -e
shopt -s nullglob

if [ ! -f mysql_connect.inc.php ]; then
  echo "Missing file mysql_connect.inc.php!"
  if [ "$1" != "--force" ]; then
    echo "Aborting... (use --force to continue)"
    exit 1
  else
    echo "Continuing anyway..."
  fi
fi

make clean
make publish

if [ -f mysql_connect.inc.php ]; then
  cp mysql_connect.inc.php output/
fi

ln -s /srv/hidden output/hidden
ln -s /srv/stuff output/stuff
ln -s /srv/photos output/photos

make rsync_publish

echo "Ready!"
